import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
      <div className=" justify-center">
          <SignedOut>
            <SignInButton/>
          </SignedOut>
          </div>
          <SignedIn>
            <UserButton/>
            <h1 className = "flex justify-center text-2xl p-4">Notes App</h1>
          <div>{ children }</div>
          </SignedIn>
          
        
      </body>
    </html>
    </ClerkProvider>
  );
}
